version: '3.9'

services:
  django:
    build: . # path to Dockerfile
    command: sh -c "
      python manage.py makemigrations
      && python manage.py migrate  
      && gunicorn --bind 0.0.0.0:8000 core_app.wsgi"
    volumes:
      - ./core_app:/project
      - ./core_app/static:/project/static
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  celery:
    build: .
    command: celery -A app worker  --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      # environment variables declared in the environment section override env_file
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  bot:
    build: bot/.
    command: python bot.py
    env_file:
      - .env




volumes:
    pg_data:
    static: