# Generated by Django 4.0 on 2022-07-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='usd_cost',
            field=models.IntegerField(),
        ),
    ]
