# Generated by Django 4.0 on 2022-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_currency_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='usd_rub',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
    ]
