# Generated by Django 4.0 on 2022-07-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
